version: 0.2 
 
phases: 
  install: 
    runtime-versions: 
      java: corretto8
      docker: 18
  pre_build: 
    commands: 
      - echo Logging in to Amazon ECR... 
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn clean package
      - docker build -t yulim-repo:latest .
      - docker tag yulim-repo:latest 125120394697.dkr.ecr.ap-northeast-2.amazonaws.com/yulim-repo:latest    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 125120394697.dkr.ecr.ap-northeast-2.amazonaws.com/yulim-repo:latest
